name: Update Timestamp

on:
  schedule:
    - cron: '30 0,3,6,9,12,15,18,21 * * *' # Every 3 hours starting at 00:30 UTC

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update timestamp in Unix epoch format
      run: |
        date +%s > timestamp.txt

    - name: Commit and push changes
      env:
        PAT_TOKEN_TIMESTAMP: ${{ secrets.PAT_TOKEN_TIMESTAMP }}
      run: |
        git config --global user.name "fz-alt"
        git config --global user.email "felix.zeitler@altruan.de"
        git add timestamp.txt
        git commit -m "Update timestamp" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN_TIMESTAMP }}@github.com/fz-alt/timestamp.git
