name: Update Timestamp

on:
  schedule:
    - cron: '30 0,3,6,9,12,15,18,21 * * *' # Adjust this if you want exact Berlin times in UTC

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update timestamp in Berlin timezone
      run: |
        TZ=Europe/Berlin date +"%Y-%m-%d %H:%M:%S" > timestamp.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "fz-alt"
        git config --global user.email "felix.zeitler@altruan.de"
        git add timestamp.txt
        git commit -m "Update timestamp"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/fz-alt/timestamp.git
