name: Update Timestamp

on:
  schedule:
    - cron: '30 0,3,6,9,12,15,18,21 * * *' # Every 3 hours starting at 00:30 UTC

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug current state
      run: |
        echo "Repository: https://github.com/fz-alt/timestamp.git"
        echo "Running as user: $(whoami)"
        echo "Current directory: $(pwd)"
        echo "Contents:"
        ls -la

    - name: Update timestamp in Berlin timezone
      run: |
        TZ=Europe/Berlin date +"%Y-%m-%d %H:%M:%S" > timestamp.txt

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "fz-alt"
        git config --global user.email "felix.zeitler@altruan.de"
        git add timestamp.txt
        git commit -m "Update timestamp" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/fz-alt/timestamp.git
